
/* Generated by Interface Builder */

#ifndef OPENSTEP
#import <appkit/Application.h>
#else /* OPENSTEP */
#import <AppKit/NSApplication.h>
#endif /* OPENSTEP */

#ifndef OPENSTEP
@interface MacAppClass:Application
#else /* OPENSTEP */
@interface MacAppClass:NSApplication
#endif /* OPENSTEP */
{
   id gameWindow;
   id game;
   id infoPanel;
   id myButton;
   id myForm;
   id serialText;
   id registerWindow;
   id registerWindow2;
   id doneButton;
   id sptext;
   id starsptext;
   id pctext;
   id starpctext;
   id d0text;
   id psltext;
   id sigtext;
   id debtext;
   id debtable;
   id deathwindow;
   id commenttext;
   id printView;
   id prefWindow;
   id myMenu;
   id serialForm;
   id serialWindow;
   id splashScreen;
   id deathMenuCell;
   id versionString;
}

#ifndef OPENSTEP
- appDidInit:app;
- windowDidBecomeKey:sender;
#else /* OPENSTEP */
- (void) windowDidBecomeKey:(NSNotification *)anotification;
- (void) windowDidResignKey:(NSNotification *)anotification;
#endif /* OPENSTEP */
- showInfo:sender;
- printGame:sender;

@end
