
/* Generated by Interface Builder */

#ifndef OPENSTEP
#import <appkit/Window.h>
#else /* OPENSTEP */
#import <AppKit/NSWindow.h>
#endif /* OPENSTEP */

#ifndef OPENSTEP
@interface MacWindow:Window
#else /* OPENSTEP */
@interface MacWindow:NSWindow
#endif /* OPENSTEP */
{
}

#ifndef OPENSTEP
- (BOOL)commandKey:(NXEvent *)theEvent;
#else /* OPENSTEP */
- (BOOL)commandKey:(NSEvent *)theEvent;
#endif /* OPENSTEP */

@end
