
/* Generated by Interface Builder */

#import <Cocoa/Cocoa.h>

@class MacViewClass;
@class MacWindow;

@interface MacAppClass : NSObject <NSWindowDelegate, NSApplicationDelegate>
{
   IBOutlet MacWindow *gameWindow;
   IBOutlet MacViewClass *game;
   IBOutlet NSPanel *infoPanel;
   IBOutlet id myButton;
   IBOutlet id myForm;
   IBOutlet id doneButton;
   IBOutlet NSTextField *sptext;
   IBOutlet NSTextField *starsptext;
   IBOutlet NSTextField *pctext;
   IBOutlet NSTextField *starpctext;
   IBOutlet NSTextField *d0text;
   IBOutlet NSTextField *psltext;
   IBOutlet NSTextField *sigtext;
   IBOutlet NSTextField *debtext;
   IBOutlet NSTextField *debtable;
   IBOutlet NSWindow *deathwindow;
   IBOutlet NSTextField *commenttext;
   IBOutlet NSWindow *prefWindow;
   IBOutlet NSMenu *myMenu;
   IBOutlet NSWindow *splashScreen;
   IBOutlet id deathMenuCell;
   IBOutlet NSTextField *versionString;
   id printView;
}

- (void) windowDidBecomeKey:(NSNotification *)anotification;
- (void) windowDidResignKey:(NSNotification *)anotification;
- (IBAction) showInfo:(id)sender;
- (IBAction) printGame:(id)sender;

@end
