
/* Generated by Interface Builder */

#import <AppKit/NSWindow.h>

namespace Executor {
  extern void ROMlib_dummywincall( void );
}

@interface MacWindow : NSWindow

- (BOOL)commandKey:(NSEvent *)theEvent;

@end
