dist: trusty
compiler: gcc
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - cmake-data
      - cmake
      - libsdl2-dev


script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
  - make
