#if !defined(__RSYS_PREFPANEL__)
#define __RSYS_PREFPANEL__

enum { PREFDIALID = -4063 };

enum
{
  PREFOKITEM			= 1,
  PREFCANCELITEM		= 2,
  PREFSAVEITEM			= 3,
  PREFNORMALITEM		= 4,
  PREFINBETWEENITEM		= 5,
  PREFANIMATIONITEM		= 6,
  PREFSOUNDOFFITEM		= 7,
  PREFSOUNDPRETENDITEM		= 8,
  PREFSOUNDONITEM		= 9,
  PREFNOCLOCKITEM		= 10,
  PREFPASSPOSTSCRIPTITEM	= 11,
  PREFNEWLINEMAPPINGITEM	= 12,
  PREFFLUSHCACHEITEM		= 13,
  PREFDIRECTDISKITEM		= 14,
  PREFNO32BITWARNINGSITEM	= 15,
  PREFFONTSUBSTITUTIONITEM	= 16,
  PREFCACHEHEURISTICSITEM	= 17,
  PREFREFRESHITEM		= 18,
  PREF_REFRESH_LABEL		= 19,
  PREF_SCREEN_UPDATES_LABEL	= 20,
  PREF_SOUND_LABEL		= 21,
  PREF_NUMBER_OF_COLORS_LABEL	= 22,
  PREF_COLORS_2			= 23,
  PREF_COLORS_4			= 24,
  PREF_COLORS_16		= 25,
  PREF_COLORS_256		= 26,
  PREF_SYSTEM			= 27,
  PREF_COMMENTS			= 28,
  PREF_SYSTEM_LABEL		= 29,
  PREF_COLORS_THOUSANDS		= 30,
  PREF_COLORS_MILLIONS		= 31,

  PREF_PRETEND_HELP             = 32,
  PREF_PRETEND_EDITION          = 33,
  PREF_PRETEND_SCRIPT           = 34,
  PREF_PRETEND_ALIAS            = 35,

  PREF_GRAY_SCALE               = 36,

  PREF_APPNAME                  = 37,
};

#endif /* !defined(__RSYS_PREFPANEL__) */
