/*
 *     Generated by the NeXT Interface Builder.
 */

#import <stdlib.h>
#import "MacAppClass.h"

void main(int argc, char *argv[]) {
    NXApp = [MacAppClass new];
    [NXApp loadNibSection:"HFS_XFer.nib" owner:NXApp];
    [NXApp run];
    [NXApp free];
    exit(0);
}
