.\" (c) 1998 by Abacus Research & Development, Inc. (ARDI)
.\"
.\" This man page is part of the commercial Executor package available
.\" from ARDI <http://www.ardi.com/>.

.TH directory_map 5  "April 10, 1998" "Executor 2.0v"
.SH NAME
directory_map \- Executor database for mapping i-numbers to names
.SH DESCRIPTION
Macintosh filesystems give the programmer the ability to look up
directories by number rather than by name.
.B Executor
needs to provide the same functionality to Macintosh applications.  So
when representing Macintosh on UNIX filesystems, it's necessary to
keep a map from UNIX filesystem and i-number to pathname.
.PP
.SH FORMAT
The format of the map is not publicly documented.
.SH FILES
/var/opt/executor/directory_map-le.db - the directory map that is shared
by all
.B executor
users on little-endian machines (e.g. 80x86 compatibles).

/var/opt/executor/directory_map.db - the directory map that is shared by all
.B executor
users on big-endian machines (e.g. NeXTstations).

.SH "SEE ALSO"
\fIexecutor\fP(1)
