set(trap_instance_sources
		trap_instances/ADB.cpp
		trap_instances/AliasMgr.cpp
		trap_instances/AppleEvents.cpp
		trap_instances/BinaryDecimal.cpp
		trap_instances/ControlMgr.cpp
		trap_instances/CQuickDraw.cpp
		trap_instances/DeskMgr.cpp
		trap_instances/DialogMgr.cpp
		trap_instances/DiskInit.cpp
		trap_instances/EditionMgr.cpp
		trap_instances/FileMgr.cpp
		trap_instances/Finder.cpp
		trap_instances/FontMgr.cpp
		trap_instances/Gestalt.cpp
		trap_instances/HelpMgr.cpp
		trap_instances/Iconutil.cpp
		trap_instances/IntlUtil.cpp
		trap_instances/ListMgr.cpp
		trap_instances/MemoryMgr.cpp
		trap_instances/MenuMgr.cpp
		trap_instances/NotifyMgr.cpp
		trap_instances/OSEvent.cpp
		trap_instances/OSUtil.cpp
		trap_instances/Package.cpp
		trap_instances/PrintMgr.cpp
		trap_instances/ProcessMgr.cpp
		trap_instances/QuickDraw.cpp
		trap_instances/QuickTime.cpp
		trap_instances/ResourceMgr.cpp
		trap_instances/SANE.cpp
		trap_instances/ScrapMgr.cpp
		trap_instances/ScriptMgr.cpp
		trap_instances/SegmentLdr.cpp
		trap_instances/ShutDown.cpp
		trap_instances/SoundMgr.cpp
		trap_instances/StdFilePkg.cpp
		trap_instances/SysErr.cpp
		trap_instances/TextEdit.cpp
		trap_instances/TimeMgr.cpp
		trap_instances/ToolboxEvent.cpp
		trap_instances/ToolboxUtil.cpp
		trap_instances/VRetraceMgr.cpp
		trap_instances/WindowMgr.cpp
		trap_instances/rsys_adb.cpp
		trap_instances/rsys_cfm.cpp
		trap_instances/rsys_ctl.cpp
		trap_instances/rsys_emustubs.cpp
		trap_instances/rsys_gestalt.cpp
		trap_instances/rsys_list.cpp
		trap_instances/rsys_menu.cpp
		trap_instances/rsys_mixed_mode.cpp
		trap_instances/rsys_osutil.cpp
		trap_instances/rsys_print.cpp
		trap_instances/rsys_refresh.cpp
		trap_instances/rsys_soundopts.cpp
		trap_instances/rsys_stdfile.cpp
		trap_instances/rsys_tesave.cpp
		trap_instances/rsys_vbl.cpp
		trap_instances/rsys_wind.cpp
	)
